AWSTemplateFormatVersion: '2010-09-09'
Description: Sniffles assets

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs:
  TemplateID:
    Description: Template reference name
    Value: 'assets'
  Region:
    Description: 'Region where stack is deployed'
    Value: !Sub '${AWS::Region}'
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
